repository: madcato/SwiftSample

install:
  - git pull
  - swift build
  - mkdir -p log

script:
  - .build/debug/SwiftSample 2> ./log/output.log

after_script:
  - git add .
  - git commit -m 'automated commit'
  - git push
