repository: madcato/SwiftSample

install:
  - git pull
  - swift build

script:
  - .build/debug/SwiftSample > output.log

after_script:
  - git add .
  - git commit -m 'automated commit'
  - git push
